CREATE SEQUENCE PASSPORT_ID_SEQUENCE START WITH 1;

CREATE TABLE PASSPORT
(
    PASSPORT_ID BIGINT,
    CODE        VARCHAR(15),
    EXPIRES_AT  TIMESTAMP WITH TIME ZONE,

    PRIMARY KEY (PASSPORT_ID)
);
