CREATE SEQUENCE PERSON_ID_SEQUENCE START WITH 1;

CREATE TABLE PERSON
(
    PERSON_ID   BIGINT,
    FIRST_NAME  VARCHAR,
    LAST_NAME   VARCHAR,
    PASSPORT_ID BIGINT,

    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (PASSPORT_ID) REFERENCES PASSPORT (PASSPORT_ID),
    UNIQUE (PASSPORT_ID)
);
